applicationApiVersion: v1beta1
x-google-marketplace:
  # MUST be v2.
  schemaVersion: v2

  # MUST match the version of the Application custom resource object.
  # This is the same as the top level applicationApiVersion field in v1.
  applicationApiVersion: v1beta1

  # The release version is required in the schema and MUST match the
  # release tag on the the deployer.
  publishedVersion: '2.4.0'
  publishedVersionMetadata:
    releaseNote: >-
      Release notes can be found here: https://docs.portworx.com/reference/release-notes/portworx/#2-7-2-1
    # releaseTypes list is optional.
    releaseTypes:
    - Feature
    - BugFix
    # If recommend is true, users using older releases are encouraged
    # to update as soon as possible. Useful if, for example, this release
    # fixes a critical issue.
    recommended: true

  # This MUST be specified to indicate that the deployer supports managed updates.
  # Note that this could be left out or kalmSupported set to false, in
  # which case the deployer uses schema v2 but does not support update.
  managedUpdates:
    kalmSupported: true

  # Image declaration is required here.
  images:
    # PX-CENTRAL
    pxcentral-onprem-api:
      properties:
        images.pxcentralApiServerImage.registry:
          type: REGISTRY
        images.pxcentralApiServerImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.pxcentralApiServerImage.tag: 
          type: TAG
    pxcentral-onprem-ui-frontend:
      properties:
        images.pxcentralFrontendImage.registry:
          type: REGISTRY
        images.pxcentralFrontendImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.pxcentralFrontendImage.tag: 
          type: TAG
    pxcentral-onprem-ui-backend:
      properties:
        images.pxcentralBackendImage.registry:
          type: REGISTRY
        images.pxcentralBackendImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.pxcentralBackendImage.tag: 
          type: TAG
    pxcentral-onprem-ui-lhbackend:
      properties:
        images.pxcentralMiddlewareImage.registry:
          type: REGISTRY
        images.pxcentralMiddlewareImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.pxcentralMiddlewareImage.tag: 
          type: TAG
    pxcentral-onprem-post-setup:
      properties:
        images.postInstallSetupImage.registry:
          type: REGISTRY
        images.postInstallSetupImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.postInstallSetupImage.tag: 
          type: TAG
    postgresql:
      properties:
        images.keycloakBackendImage.registry:
          type: REGISTRY
        images.keycloakBackendImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.keycloakBackendImage.tag: 
          type: TAG
    keycloak:
      properties:
        images.keycloakFrontendImage.registry:
          type: REGISTRY
        images.keycloakFrontendImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.keycloakFrontendImage.tag: 
          type: TAG
    keycloak-login-theme:
      properties:
        images.keycloakLoginThemeImage.registry:
          type: REGISTRY
        images.keycloakLoginThemeImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.keycloakLoginThemeImage.tag: 
          type: TAG
    busybox:
      properties:
        images.keycloakInitContainerImage.registry:
          type: REGISTRY
        images.keycloakInitContainerImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.keycloakInitContainerImage.tag: 
          type: TAG
    mysql:
      properties:
        images.mysqlImage.registry:
          type: REGISTRY
        images.mysqlImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.mysqlImage.tag: 
          type: TAG

    ## Images required for enabling px-backup
    px-backup:
      properties:
        images.pxBackupImage.registry:
          type: REGISTRY
        images.pxBackupImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.pxBackupImage.tag: 
          type: TAG
    mongodb:
      properties:
        images.mongodbImage.registry:
          type: REGISTRY
        images.mongodbImage.repo:
          type: REPO_WITHOUT_REGISTRY
        images.mongodbImage.tag: 
          type: TAG
    
    
  deployerServiceAccount:
    description: >
      Creates app resources, including the MyAppCustomResource CRD.
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
      - apiGroups: ['rbac.authorization.k8s.io', "clusterroles.rbac.authorization.k8s.io"]
        resources: ['*']
        verbs: ["*"]

properties:
  name:
    type: string
    default: "portworx"
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  pxBackupServiceAccount:
    title: PX Backup Service Account
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      title: PX Backup Service Account
      serviceAccount:
        description: Service account to assign to Portworx Operator
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['*']
            resources: ['*']
            verbs: ['create','get','update','patch','delete','list','watch','deletecollection','use','impersonate','bind','escalate']
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET
  
  # persistentStorage
  persistentStorage.enabled:
    title: Enable Persistent Storage
    description: Enable persistent storage
    type: boolean
    default: true
  persistentStorage.storageClassName:
    title: Storage Class Name
    description: Provide storage class name which exists
    type: string
    default: ""
  persistentStorage.cassandra.storage: 
    title: Volume Size for Cassandra
    description: Volume size for Cassandra
    type: string
    default: "64Gi"
  persistentStorage.grafana.storage: 
    title: Volume Size for Grafana
    description: Volume size for Grafana
    type: string
    default: "20Gi"
  persistentStorage.consul.storage: 
    title: Volume Size for Consul
    description: Volume size for Consul
    type: string
    default: "8Gi"
  persistentStorage.alertManager.storage: 
    title: Volume Size for AlertManager
    description: Volume size for cassandra
    type: string
    default: "2Gi"
  persistentStorage.ingester.storage:
    title: Volume Size for Ingester
    description: Volume size for ingester
    type: string
    default: "100Gi"
  persistentStorage.mysqlVolumeSize: 
    title: Volume Size for MySQL
    description: Volume size for MySQL
    type: string
    default: "100Gi"
  persistentStorage.mongodbVolumeSize: 
    title: Volume Size for MongoDB
    description: Volume size for MongoDB
    type: string
    default: "64Gi"
  persistentStorage.mongoCacheSize: 
    title: Cache Size for Mongo
    description: Cache size for Mongo
    type: integer
    default: 4
  persistentStorage.keycloakThemeVolumeSize: 
    title: Keycloak frontend theme volume size
    description: Keycloak frontend theme volume size
    type: string
    default: "5Gi"
  persistentStorage.keycloakBackendVolumeSize: 
    title: Keycloak backend volume size
    description: Keycloak backend volume size
    type: string
    default: "10Gi"
  
  storkRequired:
    title: Requires Stork
    description: Scheduler name as stork
    type: boolean
    default: false
  
  nodeAffinityLabel:
    title: Label for Node AFfinity
    description: Label for node affinity for px-central components
    type: string
    default: ""
  podAntiAffinity:
    title: Pod Affinity
    description: PodAntiAffinity will make sure pods are distributed 
    type: boolean
    default: false

  pxcentralDBPassword:
    title: Password for PX Central
    description: PX-Central cluster store mysql database password 
    type: string
    default: "Password1"
  caCertsSecretName:
    title: CA certs secret name
    description: Name of the Kubernetes Secret, which contains the CA Certificates
    type: string
    default: ""
  
  # oidc
  oidc.centralOIDC.enabled:
    title: Enable OIDC for PX-Central and PX-backup for RBAC
    description: Enable OIDC for PX-Central and PX-backup for RBAC
    type: boolean
    default: true
  oidc.centralOIDC.defaultUsername:
    title: Default Username for OIDC
    description: Default Username for OIDC
    type: string
    default: "admin"
  oidc.centralOIDC.defaultPassword:
    title: Default Password for OIDC
    description: Default Username for OIDC
    type: string
    default: "admin"
  oidc.centralOIDC.defaultEmail:
    title: Default Email for OIDC
    description: Default Email for OIDC
    type: string
    default: "admin@portworx.com"
  oidc.centralOIDC.keyCloakBackendUserName:
    title: Username for keycloak OIDC
    description: Username for keycloak OIDC
    type: string
    default: "keycloak"
  oidc.centralOIDC.keyCloakBackendPassword:
    title: Password for keycloak OIDC
    description: Password for keycloak backend
    type: string
    default: "keycloak"
  oidc.centralOIDC.clientId:
    title: ClientID for OIDC
    description: ClientID for OIDC
    type: string
    default: "pxcentral"
  oidc.centralOIDC.updateAdminProfile:
    title: Update admin profile for keycloak OIDC
    description: Enable/Disable admin profile update action
    type: boolean
    default: true

  
  # externalOIDC
  externalOIDC.enabled:
    title: External OIDC
    description: Enable external OIDC provider
    type: boolean
    default: false
  externalOIDC.clientID:
    title: External OIDC
    description: External OIDC Client ID
    type: string
    default: ""
  externalOIDC.clientSecret:
    title: External OIDC
    description: External OIDC Client Secret
    type: string
    default: ""
  externalOIDC.endpoint:
    title: External OIDC
    description: External OIDC Endpoint
    type: string
    default: ""

  # postInstallJob
  postInstallJob.sslEnabled:
    title: Post Install 
    description: k8s apis with ssl enabled in post-install-job pod
    type: boolean
    default: true


  # pxbackup
  # pxbackup.enabled:
  #   title: Enable PX Backup
  #   description: Enable PX Backup
  #   type: boolean
  #   default: true
  pxbackup.orgName:
    title: PX Backup organization name
    description: PX Backup organization name
    type: string
    default: "default"
  pxbackup.callHome:
    title: PX Backup Call Home
    description: PX Backup Call Home
    type: boolean
    default: true
  pxbackup.mongoMigration:
    title: PX Backup mongo migration
    description: PX Backup mongo migration
    type: string
    default: "complete"

  # pxlicenseserver
  # pxlicenseserver.enabled:
  #   title: Enable License Server
  #   description: PX-Central cluster enabled license server component
  #   type: boolean
  #   default: false
  # pxlicenseserver.internal.enabled:
  #   title: PX-Central cluster license server enabled
  #   description: PX-Central cluster license server
  #   type: boolean
  #   default: true
  # pxlicenseserver.internal.lsTypeUAT:
  #   title: Storage Drives
  #   description: PX license server deployment type [UAT]
  #   type: boolean
  #   default: false
  # pxlicenseserver.internal.lsTypeAirgapped:
  #   title: Storage Drives
  #   description: PX license server deployment type
  #   type: boolean
  #   default: false
  # pxlicenseserver.external.enabled:
  #   title: Storage Drives
  #   description: External license server enabled
  #   type: boolean
  #   default: false
  # pxlicenseserver.mainNodeIP:
  #   title: PX license server main node IP
  #   description: External license server main node endpoints
  #   type: string
  #   default: ""
  # pxlicenseserver.backupNodeIP:
  #   title: PX license server backup node IP
  #   description: External license server backup node endpoints
  #   type: string
  #   default: ""
  # pxlicenseserver.adminUserName:
  #   title: PX license server admin username
  #   description: PX license server admin username
  #   type: string
  #   default: "admin"
  # pxlicenseserver.adminUserPassword:
  #   title: PX license server admin user password
  #   description: PX license server admin user password
  #   type: string
  #   default: "Adm1n!Ur"
  
  # pxmonitor
  # pxmonitor.enabled:
  #   title: PX-Central cluster enabled monitor component
  #   description: PX-Central cluster enabled monitor component
  #   type: boolean
  #   default: false
  # pxmonitor.pxCentralEndpoint:
  #   title: PX-Central endpoint
  #   description: PX-Central endpoint (LB endpoint of px-central-ui service, ingress host) 
  #   type: string
  #   default: ""
  # pxmonitor.sslEnabled:
  #   title: PX-Central UI is accessibe on https
  #   description: PX-Central UI is accessibe on https
  #   type: boolean
  #   default: false
  # pxmonitor.oidcClientID:
  #   title: PX-Central internal oidc client ID
  #   description: PX-Central internal oidc client secret
  #   type: string
  #   default: "pxcentral"
  # pxmonitor.consulBindInterface:
  #   title: "Exclusive bind interface for consul (ex: eth0)"
  #   description: "Exclusive bind interface for consul (ex: eth0)"
  #   type: string
  #   default: ""
  # pxmonitor.cortex.alertmanager.advertiseAddress:
  #   title: Advertise address for alert manager
  #   description: Advertise address for alert manager (supported values - "pod_ip")
  #   type: string
  #   default: ""

  # service
  service.pxCentralUIServiceType: 
    title: PX Central UI service type
    description: "PX Central UI service type. To set the LoadBalancer service type to internal only. ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer"
    type: string
    default: "LoadBalancer"
  service.pxCentralUIServiceAnnotations: 
    title: PX Central UI Service Annotations
    description: PX Central UI Service Annotations
    type: string
    default: |
      {}
  service.pxBackupUIServiceType: 
    title: PX Backup UI Service Type
    description: PX Backup UI Service Type
    type: string
    default: "LoadBalancer"
  service.pxBackupUIServiceAnnotations: 
    title: PX Backup UI Service Annotations
    description: PX Backup UI Service Annotations
    type: string
    default: |
      {}
  # # service.grafanaServiceType: 
  #   title: Grafana Service Type
  #   description: Grafana Service Type
  #   type: string
  #   default: "NodePort"
  # service.cortexNginxServiceType: 
  # title: Cortex Nginx Service Type
  # description: Cortex Nginx Service Type
  # type: string
  # default: "NodePort"

  # cassandra
  # cassandra.jvm.maxHeapSize:
  #   title: Cassandra JVM max heap size
  #   description: |
  #     Memory settings: These are calculated automatically unless specified otherwise
  #     To run on environments with little resources (<= 8GB), tune your heap settings:
  #     maxHeapSize:
  #     - calculate 1/2 ram and cap to 1024MB
  #     - calculate 1/4 ram and cap to 8192MB
  #     - pick the max
  #     newHeapSize:
  #     A good guideline is 100 MB per CPU core.
  #     - min(100 * num_cores, 1/4 * heap size)
      
  #     maxHeapSize: 4G
  #     newHeapSize: 800M
  #   type: string
  #   default: ""
  # cassandra.jvm.newHeapSize:
  #   title: Cassandra JVM new heap size
  #   description: |
  #     Memory settings: These are calculated automatically unless specified otherwise
  #     To run on environments with little resources (<= 8GB), tune your heap settings:
  #     maxHeapSize:
  #     - calculate 1/2 ram and cap to 1024MB
  #     - calculate 1/4 ram and cap to 8192MB
  #     - pick the max
  #     newHeapSize:
  #     A good guideline is 100 MB per CPU core.
  #     - min(100 * num_cores, 1/4 * heap size)
      
  #     maxHeapSize: 4G
  #     newHeapSize: 800M
  #   type: string
  #   default: ""

  # installCRDs:
  #   title: Install metrics stack required CRDs
  #   description: Install metrics stack required CRDs
  #   type: boolean
  #   default: false
  # clusterDomain:
  #   title: Cluster domain
  #   description: Cluster domain
  #   type: string
  #   default: "cluster.local"
  # cassandraUsername:
  #   title: Cassandra cluster username
  #   description: Cassandra cluster username
  #   type: string
  #   default: "cassandra"
  # cassandraPassword:
  #   title: Cassandra cluster password
  #   description: Cassandra cluster password
  #   type: string
  #   default: "cassandra"

  operatorToChartUpgrade:
    title: Operator To Chart Upgrade
    description: Operator To Chart Upgrade
    type: boolean
    default: false
  
  # securityContext
  securityContext.runAsUser:
    title: Storage Drives
    description: Security context for the pod. Do not change unless you know what you are doing!
    type: integer
    default: 1000
  securityContext.fsGroup:
    title: Storage Drives
    description: Security context for the pod. Do not change unless you know what you are doing!
    type: integer
    default: 1000
  securityContext.runAsNonRoot:
    title: Storage Drives
    description: Security context for the pod. Do not change unless you know what you are doing!
    type: boolean
    default: true

required:
- name
- namespace
- persistentStorage.enabled
- persistentStorage.storageClassName
- persistentStorage.cassandra.storage 
- persistentStorage.grafana.storage 
- persistentStorage.consul.storage 
- persistentStorage.alertManager.storage 
- persistentStorage.mysqlVolumeSize 
- persistentStorage.mongodbVolumeSize 
- persistentStorage.mongoCacheSize 
- persistentStorage.keycloakThemeVolumeSize 
- persistentStorage.keycloakBackendVolumeSize 
- storkRequired
- nodeAffinityLabel
- podAntiAffinity
- pxcentralDBPassword
- caCertsSecretName
- oidc.centralOIDC.enabled
- oidc.centralOIDC.defaultUsername
- oidc.centralOIDC.defaultPassword
- oidc.centralOIDC.defaultEmail
- oidc.centralOIDC.keyCloakBackendUserName
- oidc.centralOIDC.keyCloakBackendPassword
- oidc.centralOIDC.clientId
- oidc.centralOIDC.updateAdminProfile
- externalOIDC.enabled
- externalOIDC.clientID
- externalOIDC.clientSecret
- externalOIDC.endpoint
- postInstallJob.sslEnabled
# - pxbackup.enabled
- pxbackup.orgName
- pxbackup.callHome
- pxbackup.mongoMigration
# - pxlicenseserver.enabled
# - pxlicenseserver.internal.enabled
# - pxlicenseserver.internal.lsTypeUAT
# - pxlicenseserver.internal.lsTypeAirgapped
# - pxlicenseserver.external.enabled
# - pxlicenseserver.mainNodeIP
# - pxlicenseserver.backupNodeIP
# - pxlicenseserver.adminUserName
# - pxlicenseserver.adminUserPassword
# - pxmonitor.enabled
# - pxmonitor.pxCentralEndpoint
# - pxmonitor.sslEnabled
# - pxmonitor.oidcClientID
# - pxmonitor.consulBindInterface
# - pxmonitor.cortex.alertmanager.advertiseAddress
- service.pxCentralUIServiceType 
- service.pxCentralUIServiceAnnotations 
- service.pxBackupUIServiceType 
- service.pxBackupUIServiceAnnotations 
# - service.grafanaServiceType 
# - service.cortexNginxServiceType 
# - cassandra.jvm.maxHeapSize
# - cassandra.jvm.newHeapSize
# - installCRDs
# - clusterDomain
# - cassandraUsername
# - cassandraPassword
- operatorToChartUpgrade
- securityContext.runAsUser
- securityContext.fsGroup
- securityContext.runAsNonRoot
