apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxcentral-reporting-log-dir
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pxcentral-reporting-log-dir
{{- include "px-central.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  {{- if .Values.persistentStorage.storageClassName }}
  storageClassName: {{ .Values.persistentStorage.storageClassName }}
  {{- end }}